### ISSUE TITLE
blank page is coming after instaltion - Class 'Module' not found in 

### ISSUE THREAD

**Issue by shabeeb** [gamonoid/icehrm#29]
HI , While i am trying to install,after installation , it is redirecting to login page , showing blank page, i saw the error log,its showing like this 

Fatal error: Class 'Module' not found in /Applications/MAMP/htdocs/fctools/test/hrm/src/modules.php on line 74
can you help me on this ?

**Comment by petipotame** [comment]
Hi, Same problem
Here is log detail : [11-Oct-2016 01:58:17 Asia/Colombo] PHP Fatal error:  Class '@eaDirAdminManager' not found in /volume1/web/icehrm/modules.php on line 39

**Comment by MahbbRah** [comment]
I'm also facing Same Problem here.. Just blank Screen Came up and nothing happens after all tedious Setup !

**Comment by thilinah** [comment]
It seems like you are downloading the source instead of the release. If you are downloading the source make sure you are using the vagrant box with development environment (instuctions for this can be found in README). If not you should download the latest release from https://github.com/gamonoid/icehrm/archive/v19.0.OS.zip

**Comment by shabeeb** [comment]
yes yes, its fixed
