### ISSUE TITLE
After installation not redirected to login page

### ISSUE THREAD

**Issue by alex058** [gamonoid/icehrm#61]
hi, I'm having an issue after finishing installation and automatically directed to login page. the error shown as follow:
Notice: Constant HOME_LINK_ADMIN already defined in C:\xampp\htdocs\icehrm-master\icehrm-master\src\config.base.php on line 9
Notice: Constant HOME_LINK_OTHERS already defined in C:\xampp\htdocs\icehrm-master\icehrm-master\src\config.base.php on line 10

**Comment by thilinah** [comment]
You can not use the icehrm source from the repo to directly run the web application. It should be build using ant build script we in repo.

But you can download the latest release instead and use it. You are getting this issue since you are using source instead of release.

https://github.com/gamonoid/icehrm/releases/download/v19.0.OS/icehrm_v19.0.OS.zip
