### ISSUE TITLE
ICE HRM not redirecting to login page after success installation

### ISSUE THREAD

**Issue by pavankulka** [gamonoid/icehrm#8]
Hi 

I have installed iceHRM on centos 6.5. Successfuly installed it ,but when it is not redirecting me to login page.
I am getting the error Server error 500.

Please let me know , what is the solution for this.

Pavan

**Comment by luwum** [comment]
Having the same issue with V.16.1 on centos 6.6 and php5.3.3. is there any solution out there??

**Comment by luwum** [comment]
I managed to login after commenting out line 169 in CronUtils.php.

The Issue is coming from the the CronUtils.php file. the abstract  class EmailIceTask is throwing this error 
"PHP Fatal error:  Can't inherit abstract function IceTask::execute() (previously declared abstract in EmailIceTask) in /var/www/html/hrm/classes/CronUtils.php on line 168"

**Comment by thilinah** [comment]
We recommend having php 5.6 or above for icehrm

**Comment by lyradsotnas00** [comment]
Hi,
I was able to install IceHRM v21 on fedora 27, but when I'm having an error 500 on the login page.

php7.1
mysql ver 15.1
